"""Model of the TMT primary mirror and its 492 hexagonal segments.

The mirror is made of 492 hexagonal segments arranged around a hexagonal
hole at its center. The segments are divided into 6 sectors (A, B, C, D,
E, F) arranged counter-clockwise, each containing 82 segments. A segment
is identified by its sector letter plus a number from 1-82 (e.g. "A15"),
where numbering starts at the segment(s) closest to the center hole and
increases outward, ring by ring.

Internally, every segment is placed on a standard hexagonal grid using
cube coordinates ``(q, r, s)`` with ``q + r + s == 0`` (see
:mod:`neighbors.hexgrid`). Two segments are neighbors exactly when their
cube coordinates differ by one of the six unit hex directions, so once
the mirror is modeled this way, finding neighbors is just a lookup.

Sectors B-F are geometrically identical to sector A, just rotated by 60,
120, 180, 240, and 300 degrees respectively, so only sector A's layout is
described explicitly; the rest are generated by rotation.
"""

from __future__ import annotations

from neighbors.hexgrid import HEX_DIRECTIONS, Hex

SECTORS = "ABCDEF"
SEGMENTS_PER_SECTOR = 82
SEGMENT_COUNT = len(SECTORS) * SEGMENTS_PER_SECTOR

# Sector A has 12 rings of segments around the center hole. Rings 1-10 are
# "full": ring i has i+1 segments. The mirror's outer edge is roughly
# circular rather than hexagonal, so the outer two rings are truncated:
# ring 11 is missing its innermost segment (the one closest to sector B),
# and ring 12 only exists as a short run of 6 segments in the angular
# middle of the sector.
_FULL_RINGS = 10


def _sector_a_hex(number: int) -> Hex:
    """Return the hex location of segment ``number`` within sector A."""
    if not 1 <= number <= SEGMENTS_PER_SECTOR:
        raise ValueError(f"segment number must be 1-{SEGMENTS_PER_SECTOR}")

    start = 1
    for ring in range(1, _FULL_RINGS + 1):
        count = ring + 1
        if number < start + count:
            c = number - start
            return Hex(c, -(ring + 1), ring + 1 - c)
        start += count

    # Ring 11: 11 segments (full ring would have 12), offset by one
    # position because the position closest to sector B is missing.
    ring_11_count = 11
    if number < start + ring_11_count:
        c = number - start + 1
        return Hex(c, -12, 12 - c)
    start += ring_11_count

    # Ring 12: only 6 segments, centered in the sector.
    c = number - start + 4
    return Hex(c, -13, 13 - c)


def _build_segment_maps() -> tuple[dict[str, Hex], dict[Hex, str]]:
    segment_to_hex: dict[str, Hex] = {}
    for sector_index, sector in enumerate(SECTORS):
        for number in range(1, SEGMENTS_PER_SECTOR + 1):
            location = _sector_a_hex(number)
            for _ in range(sector_index):
                location = location.rotated_left()
            segment_to_hex[f"{sector}{number}"] = location
    hex_to_segment = {location: segment for segment, location in segment_to_hex.items()}
    return segment_to_hex, hex_to_segment


# The mirror's data model: every segment id mapped to its location on the
# hex grid, and the reverse mapping used to find what (if anything) is at
# a given location.
SEGMENT_TO_HEX, HEX_TO_SEGMENT = _build_segment_maps()


def segment_sort_key(segment_id: str) -> tuple[str, int]:
    """Sort key that orders segment ids by sector letter, then number."""
    return (segment_id[0], int(segment_id[1:]))


def neighbor_by_direction(segment_id: str) -> dict[int, str]:
    """Map each hex-direction index to the neighbor of ``segment_id`` there.

    The direction indices (0-5) index into
    :data:`neighbors.hexgrid.HEX_DIRECTIONS`. Only directions that
    actually have a neighboring segment are included, so this has
    between 3 and 6 entries. This is the lower-level building block
    behind both :func:`neighbors` and the edge-sensor model in
    :mod:`neighbors.sensors`, which needs to know *which* edge each
    neighbor is on, not just the set of neighbors.

    Raises:
        ValueError: If ``segment_id`` is not a valid segment identifier.
    """
    try:
        location = SEGMENT_TO_HEX[segment_id]
    except KeyError:
        raise ValueError(f"unknown segment id: {segment_id!r}") from None

    result: dict[int, str] = {}
    for index, direction in enumerate(HEX_DIRECTIONS):
        neighbor_id = HEX_TO_SEGMENT.get(location + direction)
        if neighbor_id is not None:
            result[index] = neighbor_id
    return result


def neighbors(segment_id: str) -> list[str]:
    """Return the identifiers of the segments adjacent to ``segment_id``.

    A segment identifier is a sector letter (A-F) followed by a segment
    number (1-82), e.g. "A22". Depending on its position in the mirror, a
    segment has 3, 4, 5, or 6 neighbors.

    Raises:
        ValueError: If ``segment_id`` is not a valid segment identifier.
    """
    return sorted(neighbor_by_direction(segment_id).values(), key=segment_sort_key)
